### ISSUE TITLE
Tracker Check

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_WEB#51]
- [x] Check all cases in log
- [x] Check process log table based on log updated
- [x] Check cases in fp

**Comment by chelsymooy** [comment]
All possible cases were thrown into error log. Please consider to save api key or secret for error log
